### ISSUE TITLE
Nothing happens after enabling webserver.py

### ISSUE THREAD

**Issue by cmnascimentor** [ozzzozo/Wifi-Pineapple-Wardriving#2]
Dear ozzzozo,

First of all, let me thank you for this project. I don't understand how you can only have 15 stars on this one, it should be blowing by now.

After turning the webserver on, I get:
* Serving Flask app 'webserver'
 * Debug mode: on
 
 And nothing happens after that.
 
 I've tried to open wardrive.py after that, but since I don't get a bash CLI (it just stands there like it's loading) the pineapple doesn't assume it.
 
 Any thoughts?
 
 Cheers!

**Comment by ozzzozo** [comment]
The webserver opens the gps service on the web at port 8000, you need to visit it with your phone and allow gps.
make sure you write the https url and not just normal http.
so something like this: https://172.16.42.1:8000/
(in the screenshot it shows port 8002 because I changed it locally it should be port 8000 for you)
![image](https://user-images.githubusercontent.com/35717765/187541334-8e4fe926-5e45-4322-b4f0-4ec9308e2c12.png)
![image](https://user-images.githubusercontent.com/35717765/187542065-012cfa41-a212-43e7-8f0f-8e6c621c26ac.png)


Regarding the wardrive.py, try running it with -h 
Anyway give it a couple of seconds to load.
![image](https://user-images.githubusercontent.com/35717765/187542508-33c7241a-7dc9-43ca-83f4-fd41269de341.png)
